import { z } from "zod";
// Risk classification map
export const RISK_MAP = {
    wing_discover: "none",
    wing_connect: "none",
    wing_get_status: "none",
    wing_schema_search: "none",
    wing_param_resolve: "none",
    wing_param_get: "none",
    wing_param_set_prepare: "medium",
    wing_param_set_apply: "medium",
    wing_channel_list: "none",
    wing_channel_get: "none",
    wing_channel_adjust_fader_prepare: "medium",
    wing_channel_adjust_fader_apply: "medium",
    wing_channel_set_mute_prepare: "medium",
    wing_channel_set_mute_apply: "medium",
    wing_send_get: "none",
    wing_send_adjust_prepare: "medium",
    wing_send_adjust_apply: "medium",
    wing_routing_trace: "none",
    wing_routing_get: "none",
    wing_routing_set_prepare: "critical",
    wing_routing_set_apply: "critical",
    wing_headamp_get: "none",
    wing_headamp_set_prepare: "high",
    wing_headamp_set_apply: "high",
    wing_phantom_set_prepare: "critical",
    wing_phantom_set_apply: "critical",
    wing_scene_list: "none",
    wing_scene_recall_prepare: "critical",
    wing_scene_recall_apply: "critical",
    wing_snapshot_save_prepare: "medium",
    wing_snapshot_save_apply: "medium",
    wing_meter_catalog: "none",
    wing_meter_read: "none",
    wing_signal_check: "none",
    sound_diagnosis_start: "none",
    sound_diagnosis_next_step: "none",
    sound_diagnosis_prepare_fix: "medium",
    sound_diagnosis_apply_fix: "medium",
    wing_raw_osc_prepare: "critical",
    wing_raw_osc_apply: "critical",
    wing_raw_native_prepare: "critical",
    wing_raw_native_apply: "critical",
};
// Zod schemas
export const WingDeviceSchema = z.object({
    id: z.string(),
    ip: z.string(),
    name: z.string().optional(),
    model: z.string().optional(),
    serial: z.string().optional(),
    firmware: z.string().optional(),
});
export const AuditRecordSchema = z.object({
    id: z.string(),
    timestamp: z.string(),
    session_id: z.string(),
    operator_id: z.string().optional(),
    mode: z.enum(["read_only", "rehearsal_safe", "maintenance", "developer_raw"]),
    risk: z.enum(["none", "low", "medium", "high", "critical"]),
    tool: z.string(),
    target: z.string(),
    reason: z.string(),
    old_value: z.unknown(),
    requested_value: z.unknown(),
    readback_value: z.unknown(),
    confirmation_text: z.string().optional(),
    result: z.enum(["success", "denied", "failed", "readback_mismatch"]),
    driver: z.enum(["native", "osc", "wapi", "fake"]),
});
//# sourceMappingURL=types.js.map